add navbar-user
WildCodeSchool/orleans-php-202103-project-haras pull request #11
Opened 2021-04-15 09:48 UTC by Loic-Code

2021-04-15 11:20 UTC, bouboumael approved these changes, later dismissed

2021-04-15 12:08 UTC, LucyMerlier requested changes
see comments

2021-04-15 12:08 UTC, LucyMerlier commented on src/View/Includes/_navbar.html.twig
> +				<a class="btn-nav" href="">Contact</a>
indentation?

2021-04-15 12:20 UTC, Loic-Code commented on src/View/Includes/_navbar.html.twig
> +				<a class="btn-nav" href="">Contact</a>
Resolve on github

2021-04-15 14:34 UTC, ChristianOlmedo submitted a review, later dismissed

2021-04-15 14:50 UTC, LucyMerlier approved these changes, later dismissed

2021-04-16 08:04 UTC, ChristianOlmedo approved these changes

2021-04-16 08:06 UTC, LucyMerlier approved these changes

2021-04-16 08:06 UTC, merged