change banner for all pages
WildCodeSchool/orleans-php-202103-project-haras pull request #124
Opened 2021-04-29 15:58 UTC by bouboumael

2021-04-29 16:49 UTC, ChristianOlmedo submitted a review, later dismissed

2021-04-30 07:06 UTC, LucyMerlier requested changes
banner_course.jpg is too heavy (>200KB)

2021-04-30 07:18 UTC, ChristianOlmedo approved these changes

2021-04-30 07:24 UTC, LucyMerlier approved these changes

2021-04-30 07:24 UTC, merged