Us23 01 secure form
WildCodeSchool/orleans-php-202103-project-haras pull request #156
Opened 2021-05-04 19:32 UTC by Wowlfy

2021-05-04 20:31 UTC, Loic-Code submitted a review, later dismissed

2021-05-05 08:37 UTC, LucyMerlier requested changes
see comments + why are there changes in composer.lock?

2021-05-05 08:37 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +
there must be length validations for each of your fields

2021-05-05 08:37 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                </ul>
why a list just for one item?

2021-05-05 08:37 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                    <input type="text" class="form-control" id="phone" name="phone" placeholder="06.00.00.00.00." aria-required="true">
there is a type="tel" that is basically a type="text" but has better UX for phone users

2021-05-05 08:37 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                    <label for="email" class="form-label">
wrong "for" attribute => should be "message"

2021-05-05 09:45 UTC, bouboumael approved these changes

2021-05-05 10:02 UTC, LucyMerlier requested changes
composer lock shouldnt have had any modifications

2021-05-05 10:23 UTC, closed without merging