Us 33 05 add update
WildCodeSchool/orleans-php-202103-project-haras pull request #157
Opened 2021-05-04 20:29 UTC by Loic-Code

2021-05-04 20:54 UTC, bouboumael submitted a review, later dismissed

2021-05-05 08:21 UTC, LucyMerlier requested changes
see comment

2021-05-05 08:21 UTC, LucyMerlier commented on src/View/Admin/Includes/_show_stages.html.twig
> +    </tbody>
indentation

2021-05-05 08:26 UTC, bouboumael approved these changes, later dismissed

2021-05-05 08:38 UTC, LucyMerlier requested changes
see comment

2021-05-05 08:38 UTC, LucyMerlier commented on src/View/Admin/Includes/_show_stages.html.twig
> +    <thead>
indentation inside table tag

2021-05-05 08:45 UTC, bouboumael submitted a review, later dismissed

2021-05-05 08:47 UTC, ChristianOlmedo approved these changes, later dismissed

2021-05-05 08:50 UTC, LucyMerlier approved these changes, later dismissed

2021-05-05 08:57 UTC, merged