First init
WildCodeSchool/orleans-php-202103-project-haras pull request #3
Opened 2021-04-09 15:18 UTC by ChristianOlmedo

2021-04-09 15:23 UTC, Loic-Code submitted a review, later dismissed

2021-04-09 15:23 UTC, bouboumael approved these changes, later dismissed

2021-04-12 08:55 UTC, LucyMerlier requested changes
no title?

2021-04-12 08:55 UTC, LucyMerlier commented on src/View/layout.html.twig
>      <title>{% block title %}{% endblock %}</title>
no title?

2021-04-12 09:43 UTC, Loic-Code approved these changes

2021-04-12 09:45 UTC, bouboumael approved these changes

2021-04-12 10:03 UTC, LucyMerlier approved these changes
ok

2021-04-12 10:03 UTC, merged