add grey block in stage page
WildCodeSchool/orleans-php-202103-project-haras pull request #33
Opened 2021-04-21 12:50 UTC by ChristianOlmedo

2021-04-21 13:08 UTC, NEL45 submitted a review, later dismissed

2021-04-21 14:04 UTC, LucyMerlier requested changes
see comments

2021-04-21 14:04 UTC, LucyMerlier commented on src/Controller/StageController.php
> +    public function stage()
no return typehint?

2021-04-21 14:04 UTC, LucyMerlier commented on src/View/User/Includes/_stage_grey_block.html.twig
> +            <button class="btn-inscription" type="button">
"btn" => avoid abbreviations

2021-04-21 14:04 UTC, LucyMerlier commented on src/View/User/Includes/_stage_grey_block.html.twig
> +        <div class="stage-grey-block-title-text">
long class name => "grey-block-content"?

2021-04-21 14:19 UTC, Loic-Code approved these changes, later dismissed

2021-04-21 14:23 UTC, LucyMerlier requested changes
see comments

2021-04-21 14:23 UTC, LucyMerlier commented on src/View/User/Includes/_stage_grey_block.html.twig
> +        <div class="stage-grey-block-title-text">
"stage-grey-block-title-text" => too long

2021-04-21 14:37 UTC, Wowlfy approved these changes, later dismissed
parfait

2021-04-21 14:50 UTC, LucyMerlier requested changes
see comments

2021-04-21 14:50 UTC, LucyMerlier commented on src/View/User/Includes/_stage_grey_block.html.twig
> +        <div class="button-insc">
don't use abbreviations

2021-04-21 14:50 UTC, LucyMerlier commented on src/View/User/Includes/_stage_grey_block.html.twig
> +        <div class="grey-block">
interverting these two class names would be clearer

2021-04-21 14:57 UTC, Loic-Code approved these changes

2021-04-22 09:34 UTC, LucyMerlier approved these changes

2021-04-22 09:34 UTC, merged