US03 05 banner and text haras on Accueil
WildCodeSchool/orleans-php-202103-project-haras pull request #41
Opened 2021-04-21 14:51 UTC by NEL45

2021-04-21 14:55 UTC, LucyMerlier approved these changes, later dismissed

2021-04-21 14:58 UTC, bouboumael submitted a review, later dismissed

2021-04-22 09:32 UTC, LucyMerlier requested changes

2021-04-22 09:32 UTC, LucyMerlier commented on src/View/User/haras.html.twig
>      {% include "User/Includes/_haras_googlemap.html.twig" %}
use single quotes to be coherent

2021-04-22 10:15 UTC, Loic-Code submitted a review, later dismissed

2021-04-22 11:50 UTC, LucyMerlier submitted a review, later dismissed

2021-04-22 12:53 UTC, ChristianOlmedo approved these changes

2021-04-22 12:57 UTC, LucyMerlier approved these changes

2021-04-22 12:57 UTC, merged