Us04 04 banner and text cours
WildCodeSchool/orleans-php-202103-project-haras pull request #42
Opened 2021-04-21 14:57 UTC by NEL45

2021-04-21 15:01 UTC, bouboumael submitted a review, later dismissed
ok haras is changed because bad commit for Lucy :)

2021-04-22 09:31 UTC, LucyMerlier requested changes
see comment

2021-04-22 09:31 UTC, LucyMerlier commented on src/View/User/course.html.twig
>      {% include "User/Includes/_course_tab.html.twig" %}
use single quotes to be coherent

2021-04-22 09:53 UTC, Loic-Code approved these changes, later dismissed

2021-04-22 11:51 UTC, LucyMerlier approved these changes, later dismissed

2021-04-22 12:59 UTC, Wowlfy approved these changes
bien

2021-04-22 13:00 UTC, Wowlfy approved these changes
bien

2021-04-22 13:53 UTC, LucyMerlier approved these changes

2021-04-22 13:53 UTC, merged