Us23 01 form contact
WildCodeSchool/orleans-php-202103-project-haras pull request #83
Opened 2021-04-27 13:59 UTC by Wowlfy

2021-04-27 14:13 UTC, Loic-Code approved these changes, later dismissed

2021-04-27 15:42 UTC, LucyMerlier requested changes
see comments

2021-04-27 15:42 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                {% endblock %}
indentation

2021-04-27 15:42 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                                <input type="nom" class="form-control" >
"nom" is not an input type

2021-04-27 15:42 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                                <input type="prenom" class="form-control" >
"prenom" is not an input type

2021-04-27 15:42 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                                <input type="Telephone" class="form-control" >
"Telephone" is not an input type

2021-04-27 15:42 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                            </div>
no button to submit the form?

2021-04-27 15:42 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                            </div>
no form tag?

2021-04-28 12:54 UTC, Wowlfy commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                {% endblock %}
merci

2021-04-28 21:39 UTC, bouboumael requested changes

2021-04-28 21:39 UTC, bouboumael commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                                    <label class="form-label">Nom</label>
indentation

2021-04-28 21:39 UTC, bouboumael commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                    <label class="form-label">Telephone</label>
the same as above

2021-04-28 21:39 UTC, bouboumael commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                    <label class="form-label">Prenom</label>
your labels are not linked to your inputs. use for = "xxx" in labels and id = "xxx" in entries

2021-04-28 21:39 UTC, bouboumael commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                    <label class="form-label">Email</label>
the same as above

2021-04-28 21:39 UTC, bouboumael commented on src/View/User/Includes/_contact_grey_block.html.twig
> +                        <label class="form-label">Message</label>
the same as above

2021-04-29 07:39 UTC, bouboumael requested changes
Please delete and adding .DS_Store into .gitignore.
With this file your have 8 files changed...

2021-04-29 08:11 UTC, bouboumael submitted a review, later dismissed
6 files because fix .ds_store :)

2021-04-29 08:28 UTC, LucyMerlier requested changes
see comment

2021-04-29 08:28 UTC, LucyMerlier commented on src/View/User/Includes/_contact_grey_block.html.twig
> +    <form class="contact-grey-title" methode="POST" novalidate>
novalidate are only for testing, don't forget to take them off before pushing

2021-04-29 08:37 UTC, bouboumael submitted a review, later dismissed

2021-04-29 08:44 UTC, LucyMerlier approved these changes, later dismissed

2021-04-29 09:22 UTC, LucyMerlier approved these changes

2021-04-29 09:32 UTC, merged