add Form Inscription Stages
WildCodeSchool/orleans-php-202103-project-haras pull request #90
Opened 2021-04-28 09:11 UTC by NEL45

2021-04-28 21:44 UTC, bouboumael requested changes

2021-04-28 21:44 UTC, bouboumael commented on src/View/User/Includes/_inscription_form_stages.html.twig
> +                    <select name="experience" class="form-control">
This field is not required?

2021-04-28 21:44 UTC, bouboumael commented on src/View/User/Includes/_inscription_form_stages.html.twig
> +                    <select name="stage" class="form-control">
this field is not required?

2021-04-29 06:33 UTC, bouboumael approved these changes
ok just values for fields empty because waiting validation.

2021-04-29 08:25 UTC, LucyMerlier approved these changes

2021-04-29 08:25 UTC, merged